### PR TITLE
Fix mongoose array with enums

### PR DESCRIPTION
**Pull request by felipe-augusto**
## Pull Request checklist:

- [x] Write an explicit title for the Pull Request
- [ ] Write changes made in the CHANGELOG.md
- [x] Test manually the implemented changes
- [ ] Review my own code (indentation, syntax, style, simplicity, readability)
- [ ] Wonder if you can improve the existing code

Hi guys, I was having a problem with this mongoose schema definition:

```js
new Schema({
  permissions: [{
    type: String,
    enum: [
      "user:read",
      "user:write"
    ],
  }]
}
```

It was generating this in the `.forestadmin-schema.json` and it was breaking:

```js
{
  "field": "permissions",
  "type": [{
    "fields": [{
      "field": "type",
      "type": "String"
    }, {
      "field": "enum",
      "type": [null]
    }]
  }],
  "defaultValue": null,
  "enums": null,
  "integration": null,
  "isFilterable": true,
  "isReadOnly": false,
  "isRequired": false,
  "isSortable": true,
  "isVirtual": false,
  "reference": null,
  "inverseOf": null,
  "validations": []
}

```

The modification that I've made generates this:

```js
{
  "field": "permissions",
  "type": ["Enum"],
  "defaultValue": null,
  "enums": null,
  "integration": null,
  "isFilterable": true,
  "isReadOnly": false,
  "isRequired": false,
  "isSortable": true,
  "isVirtual": false,
  "reference": null,
  "inverseOf": null,
  "validations": []
}
```

It is still missing the "enums" and I don't believe forest admin supports this at least for now but does not break!

### CODE REVIEW

**Comment by felipe-augusto** [comment]
@arnaudbesnier can you please take a look at this?

**Comment by ChrisLahaye** [comment]
@arnaud-moncel any update?

**Comment by arnaudbesnier** [comment]
Hi @ChrisLahaye @felipe-augusto 

Thanks for the heads up, I created an internal ticket to have a look at it in the coming weeks.

**Comment by rap2hpoutre** [comment]
@ChrisLahaye @felipe-augusto Thank you for your feedback! We [just implemented this fix](https://github.com/ForestAdmin/forest-express-mongoose/pull/319) thanks to your original PR @felipe-augusto (thank you so much for this 👍 !). 

It has been released in v6.1.1. 

I close this PR, feel free to re-open if you still have issues!

**Comment by ChrisLahaye** [comment]
@rap2hpoutre Thank you. I can confirm that the schema is correctly generated now. The online UI however doesn't show any enum values but acts similar as a string array.

**Comment by felipe-augusto** [comment]
@rap2hpoutre awesome! Thank you

**Comment by rap2hpoutre** [comment]
> @rap2hpoutre Thank you. I can confirm that the schema is correctly generated now. The online UI however doesn't show any enum values but acts similar as a string array.

👍 I'm working on it! (the enum values are now in `.forestadmin-schema.json` though, it has to be implemented on frontend!).

**Comment by rap2hpoutre** [comment]
@ChrisLahaye The UI has been fixed, now you can use a multi-select to choose your enum values. let us know if it fixes your issue.

**Pull request closed without merging**
